apiVersion: apps/v1
kind: Deployment
metadata:
  name: tip-app-deployment
  labels:
    app: TIPApp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: TIPApp
  template:
    metadata:
      labels:
        app: TIPApp
    spec:
      containers:
      - image: registry.il2.dsop.io/skicamp/project-opal/tip-front-end:3d522f91
        name: TIPApp
        ports:
        - containerPort: 3000
